### ISSUE TITLE
Configuration non sauvegardée

### ISSUE THREAD

**Issue by damda58** [Sigri44/sigri_atome#2]
Bonjour,

Je ne sais pas si le problème est connu mais dans la configuration les coches ne se sauvegarde pas et retourne a leur état initiale:

New API Total Energie => toujours à oui
Vider les tables SQL à la désinstallation => toujours à non
Enregistrer le résultat en BDD => toujours à oui
Enregistrer le résultat en JSON => toujours à non

**Comment by daodevinc** [comment]
> Bonjour,
> 
> Je ne sais pas si le problème est connu mais dans la configuration les coches ne se sauvegarde pas et retourne a leur état initiale:
> 
> New API Total Energie => toujours à oui
> Vider les tables SQL à la désinstallation => toujours à non
> Enregistrer le résultat en BDD => toujours à oui
> Enregistrer le résultat en JSON => toujours à non

Bonjour,

Normalement pas de soucis, ça fonctionne chez moi. Mais à part le Drop SQL, les autres valeurs ne sont pas encore prises en comptes (mais traitées directement en code source), en attendant la doc de la nouvelle API Total.

Plusieurs MàJ sont tombés aujourd'hui, afin de corriger définitivement toutes les erreurs ($this, MySQL, etc ...).
Merci de désactiver cronHeure/Mois, et de laisser uniquement le cronMinute tant que l'API n'est pas corrigée.

Merci
