### ISSUE TITLE
Class 'object' not found

### ISSUE THREAD

**Issue by MrJuju0319** [Sigri44/sigri_atome#3]
![Capture](https://user-images.githubusercontent.com/16257583/68873149-7eae4a00-06ff-11ea-8bd8-90e8c29cbdd7.PNG)

**Comment by kalon33** [comment]
J'ai je pense le même genre de problème : la page s'affiche vide, avec les titres des éléments entre doubles accolades, comme cela arrive pour les plugins qui n'ont pas été adaptés pour Jeedom 4.0 et/ou Debian 10

**Comment by daodevinc** [comment]
WTF ! J'ai pourtant pas changé grand chose, à part ajouté un cron, et viré pas mal de ****.
Moyen d'avoir des logs détaillés ? (genre le module, ou alors dans http.error/cron_execution, des fois il y a des logs d'autres modules).
Merci

**Comment by damda58** [comment]
Pour ma part la mise à jour n'a pas créé le cron minute je l'ai fait a la main. J'ai eu ce message d'erreur mais une seul fois :
[2019-11-14 16:25:07][ERROR] : Erreur sur sigri_atome::cronMinute() : Cannot use object of type stdClass as array
au même moment sur l'appli Direct énergie ça buguais également.

**Comment by MrJuju0319** [comment]
> > le truc c'est que je n'est pas encore pu m'etre mes identifiant
> 
> Désinstalle/réinstalle le module

sa change rien :'(
PS: Je suis sur la version 4 de jeedom donc normalement pour le fichier desktop : il faut pas changer `foreach ($eqLogics as $eqLogic) {`
par 
`foreach (jeeObject::all() as $object)`
Logs : 
`[2019-11-14 17:25:41][ALERT] : Début de la mise à jour de : sigri_atome
[2019-11-14 17:25:41][ALERT] : Téléchargement du plugin...
[2019-11-14 17:25:42][ALERT] : Téléchargement de sigri_atome...
[2019-11-14 17:25:42][ALERT] : OK
[2019-11-14 17:25:42][ALERT] : Décompression du zip...
[2019-11-14 17:25:42][ALERT] : OK
[2019-11-14 17:25:42][ALERT] : Post-installation de sigri_atome...
[2019-11-14 17:25:42][ALERT] : OK`

**Comment by damda58** [comment]
Mais chez moi le plugin fonctionne en 041cdbdcc2cf6ac162d410fea263697099a9d842 (jeedom v3)

**Comment by kalon33** [comment]
@Sigri44 mais ça fonctionnait sur Jeedom v4 avant ? Pour ma part, ça n'a jamais fonctionné avant en v4 / Debian 10.

**Comment by MrJuju0319** [comment]
> @Sigri44 mais ça fonctionnait sur Jeedom v4 avant ? Pour ma part, ça n'a jamais fonctionné avant en v4 / Debian 10.

V4 sa n'a jamais fonctionné

**Comment by damda58** [comment]
Moi j'ai pas mal d'erreur comme ça : Erreur sur sigri_atome::cronMinute() : Cannot use object of type stdClass as array

Mais je suppose que c'est un problème de leur côté puisque sur l'appli c'est mort aussi ?

![Screenshot_20191115_100227_com directenergie maconso](https://user-images.githubusercontent.com/6893451/68930787-6d148300-078f-11ea-81ff-b5916d4a212b.jpg)

**Comment by MrJuju0319** [comment]
![Screenshot_20191115-102312](https://user-images.githubusercontent.com/16257583/68931970-f331c900-0791-11ea-92bf-6fdcf5a3c78b.jpg)
Moi j'ai aucun problème sur l'appli mais que sur la V4 de jeedom

**Comment by daodevinc** [comment]
> Moi j'ai pas mal d'erreur comme ça : Erreur sur sigri_atome::cronMinute() : Cannot use object of type stdClass as array
> 
> Mais je suppose que c'est un problème de leur côté puisque sur l'appli c'est mort aussi ?
> 
> ![Screenshot_20191115_100227_com directenergie maconso](https://user-images.githubusercontent.com/6893451/68930787-6d148300-078f-11ea-81ff-b5916d4a212b.jpg)

Exactement, je l'ai eu aussi. Mais il passe pas dans les logs, j'arrive pas à chopper à les logs à ce moment précis, il s'actualise trop vite.
Normalement la gestion des erreurs est faite, alors il doit retourner de la merdasse..



> ![Screenshot_20191115-102312](https://user-images.githubusercontent.com/16257583/68931970-f331c900-0791-11ea-92bf-6fdcf5a3c78b.jpg)
> Moi j'ai aucun problème sur l'appli mais que sur la V4 de jeedom

Pour l'app ça ne bug que quelques minutes / jour, il faut tomber dessus. Mais le cron peut pas se tromper :)

**Comment by MrJuju0319** [comment]
Moyen de passer sur l'api jeedom V4 ?

**Comment by MrJuju0319** [comment]
Salut, pour la V4 il faut passer en
foreach (jeeObject::all() as $object) {
Puis rectifier les nouvelle variable de jeedom v4

**Comment by damda58** [comment]
J'ai de plus en plus cette erreur (1 à 2 fois par heure) 
Erreur sur sigri_atome::cronMinute() : Cannot use object of type stdClass as array
Est-ce que tu est au courant du problème ?

**Comment by daodevinc** [comment]
> J'ai de plus en plus cette erreur (1 à 2 fois par heure)
> Erreur sur sigri_atome::cronMinute() : Cannot use object of type stdClass as array
> Est-ce que tu est au courant du problème ?

Je suis au courant, il faudrait que j'arrive à chopper le debug de $response à ce moment là. Si tu en as je suis preneur, ça défile trop vite.

Perso de minuit à 7h ce matin, c'était en erreur en permanence. En soit c'est que l'API ne doit pas resortir d'erreur, je vais essayer de catcher ça.



> Salut, pour la V4 il faut passer en
> foreach (jeeObject::all() as $object) {
> Puis rectifier les nouvelle variable de jeedom v4

Il faut que je vois pour la V4, je n'ai pas de quoi tester.

**Comment by MrJuju0319** [comment]
Je peut être ton testeur si tu veut

**Comment by damda58** [comment]
J'ai installé la dernière version pour mettre en debug les logs et te les sortir mais on dirais qu'il appel pas la bonne route avec le cronMinute J'ai ça :

[2019-11-18 19:36:06][DEBUG] : callAtomeAPI :: call API : https://esoftlink.esoftthings.com/api/xxxxx/xxxxx/graph-query-last-consumption?period=hour
[2019-11-18 19:36:07][ERROR] : checkJsonIntegrity :: La route API n'est pas correcte : {"error":"No route found for \"GET \/api\/x\/xx\/graph-query-last-consumption\""}

**Comment by daodevinc** [comment]
> J'ai installé la dernière version pour mettre en debug les logs et te les sortir mais on dirais qu'il appel pas la bonne route avec le cronMinute J'ai ça :
> 
> [2019-11-18 19:36:06][DEBUG] : callAtomeAPI :: call API : https://esoftlink.esoftthings.com/api/xxxxx/xxxxx/graph-query-last-consumption?period=hour
> [2019-11-18 19:36:07][ERROR] : checkJsonIntegrity :: La route API n'est pas correcte : {"error":"No route found for "GET /api/x/xx/graph-query-last-consumption""}

Yo, la dernière maj (de hier) à tout corrigé, il faut simplement mettre l'option "nouvelle API" désormais, normalement déjà coché. Si ça bug, uncheck/check/save pour fixer la persistence jeedom.....

la period devrait être sod

et je dois fixer les horaires des events qui marchent pas, sinon tout le reste ok.

**Comment by damda58** [comment]
Effectivement aprés avoir décoché/coché new api on récupère bien les infos. 
Par contre il y a des moments ou le login failed sur l'API mais le plugin tente quand même l'étape 2

[2019-11-19 16:43:01][DEBUG] : $login : XXXXXX
[2019-11-19 16:43:01][DEBUG] : $password : XXXXXX
[2019-11-19 16:43:01][DEBUG] : ** 1.0 - Authentification sur Atome **
[2019-11-19 16:43:02][DEBUG] : checkJsonIntegrity :: $jsonResponse : {"code":400,"message":"Validation Failed","errors":{"errors":["Login Failed"],"children":{"email":{},"plainPassword":{},"mobileInformation":{}}}}
[2019-11-19 16:43:02][DEBUG] : ** 1.1 - Enregistrement de la connexion au format JSON **
[2019-11-19 16:43:02][DEBUG] : ** 1.2 - Connexion réussie, récupération des informations en cours ... **
[2019-11-19 16:43:02][DEBUG] : ********** Etape 2 - Récupération des datas énergie **********
[2019-11-19 16:43:02][DEBUG] : callAtomeAPI :: Retrieve user details
[2019-11-19 16:43:02][DEBUG] : ********** Récupération des infos utilisateurs **********
[2019-11-19 16:43:02][ERROR] : No information found from user

Je le vois car je suis encore en mode debug.

**Comment by dsigmoun** [comment]
bonsoir à tous,

La conso journalière ne remonterait-elle pas dans Conso Minute depuis la mise à jour de cet après-midi ?

**Comment by MrJuju0319** [comment]
> bonsoir à tous,
> 
> La conso journalière ne remonterait-elle pas dans Conso Minute depuis la mise à jour de cet après-midi ?

si tu avais lue les discutions, c'est l'une des mise a jours , bonne journée

**Comment by daodevinc** [comment]
> 
> 
> Effectivement aprés avoir décoché/coché new api on récupère bien les infos.
> Par contre il y a des moments ou le login failed sur l'API mais le plugin tente quand même l'étape 2
> 
> [2019-11-19 16:43:01][DEBUG] : $login : XXXXXX
> [2019-11-19 16:43:01][DEBUG] : $password : XXXXXX
> [2019-11-19 16:43:01][DEBUG] : ** 1.0 - Authentification sur Atome **
> [2019-11-19 16:43:02][DEBUG] : checkJsonIntegrity :: $jsonResponse : {"code":400,"message":"Validation Failed","errors":{"errors":["Login Failed"],"children":{"email":{},"plainPassword":{},"mobileInformation":{}}}}
> [2019-11-19 16:43:02][DEBUG] : ** 1.1 - Enregistrement de la connexion au format JSON **
> [2019-11-19 16:43:02][DEBUG] : ** 1.2 - Connexion réussie, récupération des informations en cours ... **
> [2019-11-19 16:43:02][DEBUG] : ********** Etape 2 - Récupération des datas énergie **********
> [2019-11-19 16:43:02][DEBUG] : callAtomeAPI :: Retrieve user details
> [2019-11-19 16:43:02][DEBUG] : ********** Récupération des infos utilisateurs **********
> [2019-11-19 16:43:02][ERROR] : No information found from user
> 
> Je le vois car je suis encore en mode debug.

Ah oui bien vu, je cherchais d'où il venait lui !!! Merci.
Je fixe ça, c'est pourtant normalement un strpos de "Login Failed", mais il est passé au travers.



> 
> 
> bonsoir à tous,
> 
> La conso journalière ne remonterait-elle pas dans Conso Minute depuis la mise à jour de cet après-midi ?

Hello, si j'ai indiqué le bug, c'est lié à Jeedom qui ne semble pas prendre le timestamp mais le Date simplement, donc il cumule les datas.. Si j'arrive pas à corriger, je ferais un diff. Pareil pour le horaire, donc pour le moment cron minute = horaire = journalier.

Lié aussi à la nouvelle API, les crons récupèrent tous la même valeur, ce qui change c'est l'heure à laquelle l'appel est fait.

**Comment by daodevinc** [comment]
C'est pushé ! Update en cours.

Pour le fix des crons, je vois pas le moyen de patcher ça, étant donné que pour le moment l'API ne retourne qu'une key, avec une value qui augumente à chaque appel (consommation). A moins que je fasse un soustraction, mais il faudrait pouvoir faire un getEvent puis une soustraction, affaire à suivre.

**Comment by kalon33** [comment]
@Sigri44 Du coup doit-on ouvrir un ticket séparé pour la compatibilité Jeedom 4 / Debian 10 ?

**Comment by daodevinc** [comment]
Merci, c'est cloturé :)
