### ISSUE TITLE
Ajout consommation en € et impact CO2

### ISSUE THREAD

**Issue by kalon33** [Sigri44/sigri_atome#9]
Dans les infos indiquées le php class, on voit la consommation en € (aussi visible dans le log de debug) et l'impact CO2. Cependant, les commandes en lien ne sont pas créées dans Jeedom à la configuration d'un nouveau compte, contrairement à 3 autres : conso journalière, horaire et minute.

Est-ce possible de corriger ? Je n'ai pas trouvé la partie du code en charge de cette création (et remontant précisément les données dans Jeedom) en y regardant rapidement et n'ai donc pas pu suggérer un patch.

**Comment by daodevinc** [comment]
Effectivement ce n'est simplement pas publié car dans le principe la domotique ne s'en sert pas ?!
Précédemment avec l'ancienne API tout était mis et on pouvait aisément le stocker. Je vais essayer de rajouter cela en option, pour ceux que ça intéresse.
Mais cette API n'est que provisoire, en attendant la nouvelle route qui rechangera..

**Comment by kalon33** [comment]
Pour moi, la domotique est aussi un dashboard de ma maison, et donc un état des lieux de son impact sur l'environnement, mais aussi sur mon porte monnaie ^^ et comme il existe un plugin qui fait le diagnostic de performance énergétique du logement dans Jeedom, ça ne dénote pas trop avec ça je crois

**Comment by MrJuju0319** [comment]
moi j'aime bien voir combien d'argent de dépense par jours, mois ect

**Comment by daodevinc** [comment]
> moi j'aime bien voir combien d'argent de dépense par jours, mois ect

Ah oui moi aussi ! Mais c'est le plugin Suivi Conso qui fait ça, car il s'occupe du prix kW/h, des taxes d'acheminements, de la TVA etc :) Et il multiplie par ta consommation Atome du coup.

> Pour moi, la domotique est aussi un dashboard de ma maison, et donc un état des lieux de son impact sur l'environnement, mais aussi sur mon porte monnaie ^^ et comme il existe un plugin qui fait le diagnostic de performance énergétique du logement dans Jeedom, ça ne dénote pas trop avec ça je crois

Oui le montant j'ai répondu au dessus, je fonctionne comme ça car il prend en compte tous les plugins (atome, linky, veolia, gaz, etc).
Pour l'impact CO2, pourquoi pas ! Pour le moment API down depuis + 24h..

Quel est le plugin pour la consommation énergétique du logement.. ?!

**Comment by kalon33** [comment]
> Quel est le plugin pour la consommation énergétique du logement.. ?!

C'est le plugin Energie https://jeedom.github.io/plugin-energy2/fr_FR/ qui fait ça

> Oui le montant j'ai répondu au dessus, je fonctionne comme ça car il prend en compte tous les plugins (atome, linky, veolia, gaz, etc).

Je comprends tout à fait ton point mais ce que j'aime assez dans ce cas ci, c'est que c'est indépendant d'un autre plugin (et n'empêche pas de l'utiliser) et surtout pas de risque que je me plante dans les tarifs à renseigner ou que j'oublie de les changer au moment opportun... parfait pour les tête en l'air quoi :)

**Comment by daodevinc** [comment]
> 
> 
> > Quel est le plugin pour la consommation énergétique du logement.. ?!
> 
> C'est le plugin Energie https://jeedom.github.io/plugin-energy2/fr_FR/ qui fait ça
> 
> > Oui le montant j'ai répondu au dessus, je fonctionne comme ça car il prend en compte tous les plugins (atome, linky, veolia, gaz, etc).
> 
> Je comprends tout à fait ton point mais ce que j'aime assez dans ce cas ci, c'est que c'est indépendant d'un autre plugin (et n'empêche pas de l'utiliser) et surtout pas de risque que je me plante dans les tarifs à renseigner ou que j'oublie de les changer au moment opportun... parfait pour les tête en l'air quoi :)

Cool merci ! Je l'avais avant, mais je me souviens pas de cette fonctionnalité !
Oui je comprends aussi, je m'occupe de faire ça au mieux, quand l'API daignera répondre...

**Comment by daodevinc** [comment]
En complément, pour info, je vais arrêter le dev car ils vont pas tarder à bloquer les routes API :

```
Je suis navrée de vous informer que je ne peux donner suite à votre demande d'API.

En effet, les données collectées par la clé Atome sont uniquement disponibles via l'application "Atome" et "Total Direct Energie".

Par conséquent, ces données ne peuvent être transmises pour toutes autres utilisations.
```

**Comment by kalon33** [comment]
c'est vraiment nul de leur part d'empêcher la réutilisation...
